### ISSUE TITLE
Update to type references instead of inline types

### ISSUE THREAD

**Issue by atomb** [GaloisInc/mir-verifier#2]
Files written by `mir-json` now refer to type parameter substitutions by name, rather than by inline type definition. Adapt the parser and translator anywhere necessary to support that.

**Comment by spernsteiner** [comment]
This was done on the `ty-intern` branch, merged in a0cbed5700c1bea8d2b97d5bfab95e81b633c4cf

**Comment by spernsteiner** [comment]
The representation of types and generics has been totally overhauled in mir-json and mir-verifier since this was opened
