### ISSUE TITLE
'cabal v2-install' doesn't copy anything to ~/.cabal/bin

### ISSUE THREAD

**Issue by fshaked** [GaloisInc/mir-verifier#24]
I'm following the instructions in README.md.
The test suite runs and everything passes, so I think I did everything correctly.
Except, there is nothing in ~/.cabal/bin.

```
$ cabal v2-install -v
[...]
Resolving dependencies...
Up to date
creating /tmp/cabal-install.-26129/dist-newstyle/build
creating /tmp/cabal-install.-26129/dist-newstyle/tmp
creating /home/sflur/.cabal/bin

$ ls -l ~/.cabal/bin
total 0
```

**Comment by spernsteiner** [comment]
It seems some versions of cabal-install require an explicit indication of what to install (haskell/cabal#5978).  Please try running `cabal v2-install crux-mir` - if that works for you, then I'll update the readme.

**Comment by fshaked** [comment]
That did the trick.

Thanks
